### PR TITLE
feat: SR PHPStan version upgraded to 1.8.0

### PR DESCRIPTION
**Pull request by jeethufoc**
Upgrade PHPStan and its dependent libraries in SR
Ticket - [LSI-1566](https://oat-sa.atlassian.net/browse/LSI-1566)

### CODE REVIEW

**Review by SergiiTao — APPROVED** [review]
works as expected

**Review by SergiiTao — CHANGES_REQUESTED** [review]
I see a lot of updates in lock. I don't think all are really required

**Review by mianchenia — APPROVED** [review]

**Review by SergiiTao — APPROVED** [review]
works as expected

**Review by chinnu-focaloid — APPROVED** [review]
Works for me

**Pull request merged**
